{
 "title": "Weather",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Current Outside", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperature",
     "measurement": "Temperature",
     "query": "SELECT mean(\"value\") *  9/5 + 32 FROM \"Temperature\" GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "*  9/5 + 32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current FeelsLike ",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperature",
     "measurement": "FeelsLike",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "measurement": "Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Wind Speed",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "WindSpeed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Heading",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WindHeading",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Current Inside", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Temperature",
     "measurement": "inside-Temperature",
     "query": "SELECT mean(\"value\") *  9/5 + 32 FROM \"Temperature\" GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "*  9/5 + 32" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Humidity",
     "measurement": "inside-Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inside-BarometricPressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 33.8639" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  { "title": "Historical Outside", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 9/5 + 32" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "WindChill",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WindChill",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "HeatIndex",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HeatIndex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "FeelsLike",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "FeelsLike",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Humidity Percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "WindSpeed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "yaxes": [
    { "format": "velocitymph" }
   ],
   "targets": [
    {
     "alias": "WindSpeed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "WindSpeed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Historical Inside", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Inside Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inside-Temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 9/5 + 32" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "WindChill",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inside-HeatIndex",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "INHG",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inside-BarometricPressure",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 33.8639" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Inside Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Humidity Percentage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "inside-Humidity",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Records", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Highest Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Temperature",
     "query": "SELECT max(\"value\")  *  9/5 +32  FROM \"Temperature\" \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " *  9/5 +32 " ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lowest Temp",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Temperature",
     "query": "SELECT (min(\"value\")  *  9/5 +32) FROM \"Temperature\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ " *  9/5 +32 " ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Max",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "WindSpeed",
     "query": "SELECT max(\"value\") FROM \"WindSpeed\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lowest WindChill",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Temperature",
     "query": "SELECT (min(\"value\") ) FROM \"WindChill\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ " *  9/5 +32 " ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Highest Temp Date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "Time" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "Temperature",
     "query": "SELECT max(\"value\"), temp FROM \"Temperature\" \n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " *  9/5 +32 " ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lowest Temp Date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Temperature",
     "query": "SELECT (min(\"value\")  *  9/5 +32), time FROM \"Temperature\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ " *  9/5 +32 " ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Lowest Temp Date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "measurement": "Temperature",
     "query": "SELECT (max(\"value\")), time FROM \"WindSpeed\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       },
       { "params": [ " *  9/5 +32 " ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "WindChill Max Date",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "velocitymph" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "WindSpeed",
     "query": "SELECT (min(\"value\")), time FROM \"WindChill\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  }
 ]
}